app/views/zhihu.py
from flask import Blueprint, render_template, redirect, request, flash, url_for

from app.models import User, ChangeLog, Feedback
import pandas as pd
import os
import time

zhihu = Blueprint(
    "zhihu", __name__, template_folder="../templates", static_folder="../static"
)
key_word_dict = {
    "chinese": "语文",
    "math": "数学",
    "english": "英语",
    "physics": "物理",
    "chemistry": "化学",
    "biology": "生物",
    "political": "政治",
    "history": "历史",
    "geography": "地理",
}

from psutil import *
from flask import jsonify
@zhihu.route("/hyakki/")
def hyakki():
   dict = {
      "memory": [virtual_memory().percent],
      "disk": [disk_usage("/").percent],
      "cpu": [cpu_percent(0)]
   }
   return jsonify(dict)


@zhihu.route("/")
def home():
    global key_word_dict
    result_df = pd.DataFrame(
        columns=["category", "category_zh", "columnsSum", "articlesSum"]
    )
    # 获取每个分类下的专栏数
    path = "app/static/data/zhihu"
    column = path + "/columns"
    date = max(os.listdir(column))
    i = 1
    for category in os.listdir(column + "/" + date + "/"):
        df = pd.read_excel(column + "/" + date + "/" + category)
        articles_sum = df["articlesCount"].sum()
        result_df.loc[i] = [
            category[:-5],
            key_word_dict[category[:-5]],
            len(df),
            articles_sum,
        ]
        i += 1
    columnsSums = result_df["columnsSum"].sum()
    articlesSums = result_df["articlesSum"].sum()
    rank = [i for i in range(1, len(result_df) + 1)]

    delta_df = pd.read_excel("app/static/data/zhihu/deltaChange/{date}.xlsx".format(date=date))

    delta_follower_top10 = delta_df.sort_values(by="deltaFollower", ascending=False)[:10]
    delta_follower_top10.index = range(1, len(delta_follower_top10) + 1)

    delta_voteup_top10 = delta_df.sort_values(by="deltaVoteupCount", ascending=False)[:10]
    delta_voteup_top10.index = range(1, len(delta_voteup_top10) + 1)

    delta_comment_top10 = delta_df.sort_values(by="deltaCommentCount", ascending=False)[:10]
    delta_comment_top10.index = range(1, len(delta_comment_top10) + 1)

    delta_rank = [i for i in range(1, len(delta_comment_top10) + 1)]
    result_df = result_df.to_dict()
    return render_template(
        "beagle/index.html",
        active="home",
        rank=rank,
        title="首页",
        result_df=result_df,
        delta_follower_top10=delta_follower_top10,
        delta_voteup_top10=delta_voteup_top10,
        delta_comment_top10=delta_comment_top10,
        delta_rank=delta_rank,
        columnsSums=columnsSums,
        articlesSums=articlesSums,
    )


@zhihu.route("/<category>")
def zhuanlan(category):
    global key_word_dict
    path = "app/static/data/zhihu/columns/"
    update_time = max(os.listdir(path))
    if os.path.exists(
            path
            + "{updateTime}/{category}.xlsx".format(
                updateTime=update_time, category=category
            )
    ):
        df = pd.read_excel(
            path
            + "{updateTime}/{category}.xlsx".format(
                updateTime=update_time, category=category
            ),
            index_col=0,
        )
    else:
        return render_template("beagle/pages-404.html"), 404

    rank = [i for i in range(1, len(df) + 1)]
    df = df.to_dict(orient="dict")
    return render_template(
        "beagle/column.html",
        rank=rank,
        updateTime=update_time.split("-"),
        category=category,
        title=key_word_dict[category],
        active=category,
        df=df,
    )


@zhihu.route("/<category>/<columnID>")
def article(category, columnID):
    global key_word_dict
    column_dir = ""
    path = "app/static/data/zhihu/articles/"
    update_time = max(os.listdir(path))
    try:
        column_articles_dir = os.listdir(
            path + update_time + "/{category}".format(category=category)
        )
    except EOFError:
        return render_template("beagle/pages-404.html"), 404
    for i in column_articles_dir:
        if columnID == i[:-5]:
            column_dir = (
                    path + update_time + "/{category}/".format(category=category) + i
            )
    if os.path.exists(column_dir):
        df = pd.read_excel(column_dir, index_col=0)
    else:
        return render_template("beagle/pages-404.html"), 404
    df = df.sort_values(by="articleUpdatedTime", ascending=False)
    rank = [i for i in range(1, len(df) + 1)]
    article_updated_time = []
    for i in range(1, len(df) + 1):
        article_updated_time.append(
            time.strftime("%Y/%m/%d", time.localtime(df.loc[i, "articleUpdatedTime"]))
        )
    path = "app/static/data/zhihu/columns/{updateTime}/{category}.xlsx".format(
        updateTime=update_time, category=category
    )
    columns = pd.read_excel(path, index_col=0)
    for i in range(len(columns)):
        if columnID == columns.iloc[i, 1].split("/")[-1]:
            column_name = columns.iloc[i, 0]
            column_url = columns.iloc[i, 1]
            author_name = columns.iloc[i, 2]
            author_url = columns.iloc[i, 3]
    df = df.to_dict()
    return render_template(
        "beagle/article.html",
        rank=rank,
        columnName=column_name,
        columnUrl=column_url,
        title=column_name,
        category=key_word_dict[category],
        active=category,
        df=df,
        authorName=author_name,
        authorUrl=author_url,
        article_updated_time=article_updated_time,
    )


@zhihu.route("/feedback", methods=["GET", "POST"])
def feedback():
    #descriptions = Feedback
    feedbacks = Feedback.query.order_by(Feedback.id.desc())
    #print(feedbacks)
    if request.method == "POST":
        description = request.form.get("description")
        contact_details = request.form.get("contact_details")
        f = Feedback()
        f.description = description
        f.contact_details = contact_details
        f.save()
        print(description, contact_details)
        flash("反馈提交成功，我们将会尽快处理!")
        return redirect(url_for('zhihu.home'))
    return render_template("beagle/feedback.html", title="反馈", feedbacks=feedbacks, f = "feedback")

@zhihu.route("/documentation")
def documentation():
    return render_template("beagle/documentation.html", docs="docs", title="文档")

app/templates/beagle/base.html
<!DOCTYPE html>
<html lang="zh">
<script>
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?7755cea1ce3f2331435d9abccc484b42";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https'){
   bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
  }
  else{
  bp.src = 'http://push.zhanzhang.baidu.com/push.js';
  }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="高中数学的奇技淫巧，知乎专栏排名，Zzmath">
    <meta name="author" content="duansq">
    <link rel="shortcut icon" href="../../static/assets/img/logo-fav.png">
    {% if title %}
        <title>{{ title }} - Zzmath</title>
    {% else %}
        <title>Zzmath</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="../../static/assets/lib/perfect-scrollbar/css/perfect-scrollbar.css"/>
    <link rel="stylesheet" type="text/css"
          href="../../static/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="../../static/assets/css/app.css" type="text/css"/>
</head>
<body>
<div class="be-wrapper be-fixed-sidebar {% if docs=="docs" %}be-aside{% endif %}">
    <nav class="navbar navbar-default navbar-fixed-top be-top-header">
        <!-- Top bar -->
        <nav class="navbar navbar-expand fixed-top be-top-header">
            <div class="container-fluid">
                <div class="be-navbar-header"><a class="navbar-brand" href="{{ url_for("zhihu.home") }}"></a>
                </div>
                {#                <div class="page-title"><span>Blank Page</span></div>#}
                <div class="be-right-navbar">
                    <ul class="nav navbar-nav float-right be-user-nav">
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#"
                                                         data-toggle="dropdown"
                                                         role="button" aria-expanded="false">
                            <span class="user-name">Zzmath</span></a>
                            <div class="dropdown-menu" role="menu">
                                <div class="user-info">
                                    <div class="user-position online">Beagle</div>
                                </div>
                                {% if title != "首页" %}
                                    <a class="dropdown-item" href="{{ url_for("zhihu.home") }}"><i
                                            class="icon mdi mdi-home"></i><span>回到主页</span></a>
                                {% endif %}
                                {% if title != "反馈" %}
                                    <a class="dropdown-item" href="{{ url_for("zhihu.feedback") }}">
                                        <span class="icon mdi mdi-comment-outline"></span>反馈意见</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav float-right be-icons-nav">
                        {#                        <li class="nav-item dropdown"><a class="nav-link be-toggle-right-sidebar" href="#" role="button"#}
                        {#                                                         aria-expanded="false">#}
                        {#                            <span class="icon mdi mdi-settings"></span></a>#}
                        {#                        </li>#}
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#"
                                                         data-toggle="dropdown"
                                                         role="button" aria-expanded="false"><span
                                class="icon mdi mdi-apps"></span></a>
                            <ul class="dropdown-menu be-connections">
                                <li>
                                    <div class="list">
                                        <div class="content">
                                            <div class="row">
                                                <div class="col"><a class="connection-item" target="_blank"
                                                                    href="https://www.zhihu.com/people/zerostwo"><img
                                                        src="../../static/assets/img/zhihu.png"
                                                        alt="Slack"><span>知乎</span></a>
                                                </div>
                                                <div class="col"><a class="connection-item" target="_blank"
                                                                    href="https://weibo.com/u/3764641951"><img
                                                        src="../../static/assets/img/weibo.png"
                                                        alt="Bitbucket"><span>微博</span></a></div>
                                                <div class="col"><a class="connection-item" target="_blank"
                                                                    href="https://github.com/zerostwo"><img
                                                        src="../../static/assets/img/github.png" alt="Github"><span>GitHub</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="footer"><a href="#">关注我的动态</a></div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </nav>
    <div class="be-left-sidebar">
        <!-- Left sidebar -->
        <div class="be-left-sidebar">
            <div class="left-sidebar-wrapper"><a class="left-sidebar-toggle" href="#"><b>{{ title }}</b></a>
                <div class="left-sidebar-spacer">
                    <div class="left-sidebar-scroll">
                        <div class="left-sidebar-content">
                            <ul class="sidebar-elements">
                                <li class="divider">Menu</li>
                                <li class="{% if active == "home" %}active{% endif %}"><a
                                        href="{{ url_for("zhihu.home") }}"><i
                                        class="icon mdi mdi-home"></i><span>主页</span></a></li>
                                <li class="parent"><a href="#"><i class="icon mdi mdi-calendar-alt"></i><span>高考</span></a>
                                    <ul class="sub-menu">
                                        <li class="{% if active == "chinese" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="chinese") }}">语文</a></li>
                                        <li class="{% if active == "math" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="math") }}">数学</a></li>
                                        <li class="{% if active == "english" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="english") }}">英语</a></li>
                                        <li class="{% if active == "physics" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="physics") }}">物理</a></li>
                                        <li class="{% if active == "chemistry" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="chemistry") }}">化学</a></li>
                                        <li class="{% if active == "biology" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="biology") }}">生物</a></li>
                                        <li class="{% if active == "political" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="political") }}">政治</a></li>
                                        <li class="{% if active == "history" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="history") }}">历史</a></li>
                                        <li class="{% if active == "geography" %}active{% endif %}"><a
                                                href="{{ url_for("zhihu.zhuanlan", category="geography") }}">地理</a></li>
                                    </ul>
                                </li>
                                <li class="{% if f == "feedback" %}active{% endif %}"><a
                                    href="{{ url_for("zhihu.feedback") }}"><i
                                    class="icon mdi mdi-comment-alert"></i><span>反馈</span></a></li>
                                <li class="{% if docs == "docs" %}active{% endif %}"><a
                                        href="{{ url_for("zhihu.documentation") }}"><i
                                        class="icon mdi mdi-file-text"></i><span>文档</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="progress-widget">
                    <div class="progress-data text-center">
                        <i class="icon mdi mdi-time"></i>
                        本站已安全运行了
                        <script language="JavaScript" type="text/javascript">var urodz = new Date("02/28/2020");
                        var now = new Date();
                        var ile = now.getTime() - urodz.getTime();
                        var dni = Math.floor(ile / (1000 * 60 * 60 * 24));
                        document.write(+dni)</script>
                        天
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="be-content {% if docs=="docs" %}docs{% endif %} ">

        {% block content %}
            <!-- Main content -->
        {% endblock %}
        <p class="text-center">Copyright © <a href="https://zzmath.top" style="color: #404040">Zzmath</a> 2020-2021
            <img style="width: 16px;vertical-align: sub;" src="../../static/filing.png">
            <a href="http://www.beian.miit.gov.cn" style="color: #404040">蜀ICP备18027889号-1</a></p>
    </div>
</div>
<script src="../../static/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
<script src="../../static/assets/lib/perfect-scrollbar/js/perfect-scrollbar.min.js"
        type="text/javascript"></script>
<script src="../../static/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
<script src="../../static/assets/js/app.js" type="text/javascript"></script>
{% block script %}
{% endblock %}
<script type="text/javascript">
    $(document).ready(function () {
        //-initialize the javascript
        App.init();
        {% block App %}
        {% endblock %}
    });
</script>
</body>
</html>

app/templates/beagle/index.html
{% extends "beagle/base.html" %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="../../static/assets/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css"/>
    <link rel="stylesheet" type="text/css" href="../../static/assets/lib/jqvmap/jqvmap.min.css"/>
    <link rel="stylesheet" type="text/css"
          href="../../static/assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
{% endblock %}
{% block content %}
    <div class="main-content container-fluid">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span
                                class="mdi mdi-close" aria-hidden="true"></span></button>
                        <div class="icon"><span class="mdi mdi-check"></span></div>
                        <div class="message">{{ message }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-contrast alert-primary alert-dismissible" role="alert">
                    <div class="icon"><span class="mdi mdi-notifications"></span></div>
                    <div class="message">
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span
                                class="mdi mdi-close"
                                aria-hidden="true"></span>
                        </button>
                        <strong>反馈:</strong> 你可以点击<a href="{{ url_for("zhihu.feedback") }}"
                                                     style="color: orangered">这里</a>来对我们进行网站优化方面的反馈意见
                    </div>
                </div>
            {% endif %}
        {% endwith %}
               <div class="alert alert-success alert-dismissible" role="alert">
                    <div class="icon"><span class="mdi mdi-notifications"></span></div>
                    <div class="message">
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span
                                class="mdi mdi-close"
                                aria-hidden="true"></span>
                        </button>
                        <strong>QQ群:572537548</strong>我们建立了一个专门面向中学生的讨论交流群，大家有问题欢迎进群讨论，目前群成员900+!
                    </div>
                </div>
                <div class="alert alert-contrast alert-danger alert-dismissible" role="alert">
                    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
                    <div class="message">
                      <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button><strong>警告！</strong> 由于知乎反爬机制升级，因此本网站数据最新来源时间为2020年09月14日！
                    </div>
                  </div>
        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card card-table card-border-color card-border-color-primary">
                    <div class="card-header">
                        <div class="title">收录专栏情况</div>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-striped table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center">序号</th>
                                <th class="text-center">类别</th>
                                <th class="text-center">专栏数</th>
                                <th class="text-center">文章数</th>
                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            {% for i in rank %}
                                <tr>
                                    <td class="text-center">{{ i }}</td>
                                    <td class="text-center"><a
                                            href="{{ url_for("zhihu.zhuanlan", category=result_df["category"][i]) }}">{{ result_df["category_zh"][i] }}</a>
                                    </td>
                                    <td class="text-center">{{ result_df["columnsSum"][i] }}</td>
                                    <td class="text-center">{{ '{0:0,.0f}'.format(result_df["articlesSum"][i]) }}</td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td class="text-center">#</td>
                                <td class="text-center">合计</td>
                                <td class="text-center">{{ columnsSums }}</td>
                                <td class="text-center">{{ '{0:0,.0f}'.format(articlesSums) }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6">
                <div class="card card-table card-border-color card-border-color-primary">
                    <div class="card-header">
                        <div class="title">昨日最受关注的专栏(Top10)</div>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-striped table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center">排名</th>
                                <th class="text-center">专栏名</th>
                                <th class="text-center">创建者</th>
                                <th class="text-center">新增关注数</th>
                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            {% for i in delta_rank %}
                                <tr>
                                    <td class="text-center">{{ i }}</td>
                                    <td class="text-center"><a href="{{ delta_follower_top10["columnUrl"][i] }}">
                                        {{ delta_follower_top10["columnName"][i] }}</a></td>
                                    <td class="text-center"><a href="{{ delta_follower_top10["authorUrl"][i] }}">
                                        {{ delta_follower_top10["authorName"][i] }}</a></td>
                                    <td class="text-center">{{ delta_follower_top10["deltaFollower"][i] }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card card-table card-border-color card-border-color-primary">
                    <div class="card-header">
                        <div class="title">昨日获得赞同最多的专栏(Top10)</div>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-striped table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center">排名</th>
                                <th class="text-center">专栏名</th>
                                <th class="text-center">创建者</th>
                                <th class="text-center">新增赞同数</th>
                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            {% for i in delta_rank %}
                                <tr>
                                    <td class="text-center">{{ i }}</td>
                                    <td class="text-center"><a href="{{ delta_voteup_top10["columnUrl"][i] }}">
                                        {{ delta_voteup_top10["columnName"][i] }}</a></td>
                                    <td class="text-center"><a href="{{ delta_voteup_top10["authorUrl"][i] }}">
                                        {{ delta_voteup_top10["authorName"][i] }}</a></td>
                                    <td class="text-center">{{ delta_voteup_top10["deltaVoteupCount"][i] }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6">
                <div class="card card-table card-border-color card-border-color-primary">
                    <div class="card-header">
                        <div class="title">昨日讨论最多的专栏(Top10)</div>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-striped table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center">排名</th>
                                <th class="text-center">专栏名</th>
                                <th class="text-center">创建者</th>
                                <th class="text-center">新增评论数</th>
                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            {% for i in delta_rank %}
                                <tr>
                                    <td class="text-center">{{ i }}</td>
                                    <td class="text-center"><a href="{{ delta_comment_top10["columnUrl"][i] }}">
                                        {{ delta_comment_top10["columnName"][i] }}</a></td>
                                    <td class="text-center"><a href="{{ delta_comment_top10["authorUrl"][i] }}">
                                        {{ delta_comment_top10["authorName"][i] }}</a></td>
                                    <td class="text-center">{{ delta_comment_top10["deltaCommentCount"][i] }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card card-border-color card-border-color-warning">
                    <div class="card-header">网站更新日志</div>
                    <div class="card-body">
                        <ul class="user-timeline user-timeline-compact">
                            <li class="latest">
                                <div class="user-timeline-date">2020年3月15日</div>
                                <div class="user-timeline-title">Version 1.1.0</div>
                                <div class="user-timeline-description">网站页面全面更新，并且提高了手机端浏览页面的舒适度...<a
                                        href="{{ url_for("zhihu.documentation", _anchor="v1.1.0") }}">更多</a>
                                </div>
                            </li>
                            <li>
                                <div class="user-timeline-date">2020年03月10日</div>
                                <div class="user-timeline-title">Version 1.0.2</div>
                                <div class="user-timeline-description">添加了语文，英语，物理等8个科目的排名信息...<a
                                        href="{{ url_for("zhihu.documentation", _anchor="v1.0.2") }}">更多</a>
                                </div>
                            </li>
                            <li>
                                <div class="user-timeline-date">2020年03月06日</div>
                                <div class="user-timeline-title">Version 1.0.1</div>
                                <div class="user-timeline-description">更换了前端模板，添加了搜索排序等功能...<a
                                        href="{{ url_for("zhihu.documentation", _anchor="v1.0.1") }}">更多</a>
                                </div>
                            </li>
                            <li>
                                <div class="user-timeline-date">2020年02月28日</div>
                                <div class="user-timeline-title">Version 1.0.0</div>
                                <div class="user-timeline-description">初始版本发行...
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="../../static/assets/js/app-charts-sparkline.js" type="text/javascript"></script>
    <script src="../../static/assets/lib/jquery.sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
{% endblock %}
{% block App %}
    App.chartsSparklines();
{% endblock %}