app/views/wechat.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
import hashlib
from flask import make_response
import xml.etree.ElementTree as ET

wechat = Blueprint(
      "wechat", __name__, template_folder="../templates", static_folder="../static")

WX_TOKEN = 'duansq'

@wechat.route("/wechat_api/", methods=['GET', 'POST'])
def index():
   if request.method == 'GET':
      token = WX_TOKEN
      data = request.args
      signature = data.get('signature', '')
      timestamp = data.get('timestamp', '')
      nonce = data.get('nonce', '')
      echostr = data.get('echostr', '')
      s = sorted([timestamp, nonce, token])
      # 字典排序
      s = ''.join(s)
      if hashlib.sha1(s.encode('utf-8')).hexdigest() == signature:
         # 判断请求来源，并对接受的请求转换为utf-8后进行sha1加密
         response = make_response(echostr)
         return response


def message_del(content): 
   # 次数是自定义的消息处理函数，自由发挥
   if "baidu" in content:
      message = "www.baidu.com"
   elif "金牛" in content:
      message = "贪财好色小心眼"
   else:
      message = "我不知道！"
   return message

app/views/zhihu.py
from flask import Blueprint, render_template, redirect, request, flash, url_for

from app.models import User, ChangeLog, Feedback
import pandas as pd
import os
import time

zhihu = Blueprint(
    "zhihu", __name__, template_folder="../templates", static_folder="../static"
)
key_word_dict = {
    "chinese": "语文",
    "math": "数学",
    "english": "英语",
    "physics": "物理",
    "chemistry": "化学",
    "biology": "生物",
    "political": "政治",
    "history": "历史",
    "geography": "地理",
}

from psutil import *
from flask import jsonify
@zhihu.route("/hyakki/")
def hyakki():
   dict = {
      "memory": [virtual_memory().percent],
      "disk": [disk_usage("/").percent],
      "cpu": [cpu_percent(0)]
   }
   return jsonify(dict)


@zhihu.route("/")
def home():
    global key_word_dict
    result_df = pd.DataFrame(
        columns=["category", "category_zh", "columnsSum", "articlesSum"]
    )
    # 获取每个分类下的专栏数
    path = "app/static/data/zhihu"
    column = path + "/columns"
    date = max(os.listdir(column))
    i = 1
    for category in os.listdir(column + "/" + date + "/"):
        df = pd.read_excel(column + "/" + date + "/" + category)
        articles_sum = df["articlesCount"].sum()
        result_df.loc[i] = [
            category[:-5],
            key_word_dict[category[:-5]],
            len(df),
            articles_sum,
        ]
        i += 1
    columnsSums = result_df["columnsSum"].sum()
    articlesSums = result_df["articlesSum"].sum()
    rank = [i for i in range(1, len(result_df) + 1)]

    delta_df = pd.read_excel("app/static/data/zhihu/deltaChange/{date}.xlsx".format(date=date))

    delta_follower_top10 = delta_df.sort_values(by="deltaFollower", ascending=False)[:10]
    delta_follower_top10.index = range(1, len(delta_follower_top10) + 1)

    delta_voteup_top10 = delta_df.sort_values(by="deltaVoteupCount", ascending=False)[:10]
    delta_voteup_top10.index = range(1, len(delta_voteup_top10) + 1)

    delta_comment_top10 = delta_df.sort_values(by="deltaCommentCount", ascending=False)[:10]
    delta_comment_top10.index = range(1, len(delta_comment_top10) + 1)

    delta_rank = [i for i in range(1, len(delta_comment_top10) + 1)]
    result_df = result_df.to_dict()
    return render_template(
        "beagle/index.html",
        active="home",
        rank=rank,
        title="首页",
        result_df=result_df,
        delta_follower_top10=delta_follower_top10,
        delta_voteup_top10=delta_voteup_top10,
        delta_comment_top10=delta_comment_top10,
        delta_rank=delta_rank,
        columnsSums=columnsSums,
        articlesSums=articlesSums,
    )


@zhihu.route("/<category>")
def zhuanlan(category):
    global key_word_dict
    path = "app/static/data/zhihu/columns/"
    update_time = max(os.listdir(path))
    if os.path.exists(
            path
            + "{updateTime}/{category}.xlsx".format(
                updateTime=update_time, category=category
            )
    ):
        df = pd.read_excel(
            path
            + "{updateTime}/{category}.xlsx".format(
                updateTime=update_time, category=category
            ),
            index_col=0,
        )
    else:
        return render_template("beagle/pages-404.html"), 404

    rank = [i for i in range(1, len(df) + 1)]
    df = df.to_dict(orient="dict")
    return render_template(
        "beagle/column.html",
        rank=rank,
        updateTime=update_time.split("-"),
        category=category,
        title=key_word_dict[category],
        active=category,
        df=df,
    )


@zhihu.route("/<category>/<columnID>")
def article(category, columnID):
    global key_word_dict
    column_dir = ""
    path = "app/static/data/zhihu/articles/"
    update_time = max(os.listdir(path))
    try:
        column_articles_dir = os.listdir(
            path + update_time + "/{category}".format(category=category)
        )
    except EOFError:
        return render_template("beagle/pages-404.html"), 404
    for i in column_articles_dir:
        if columnID == i[:-5]:
            column_dir = (
                    path + update_time + "/{category}/".format(category=category) + i
            )
    if os.path.exists(column_dir):
        df = pd.read_excel(column_dir, index_col=0)
    else:
        return render_template("beagle/pages-404.html"), 404
    df = df.sort_values(by="articleUpdatedTime", ascending=False)
    rank = [i for i in range(1, len(df) + 1)]
    article_updated_time = []
    for i in range(1, len(df) + 1):
        article_updated_time.append(
            time.strftime("%Y/%m/%d", time.localtime(df.loc[i, "articleUpdatedTime"]))
        )
    path = "app/static/data/zhihu/columns/{updateTime}/{category}.xlsx".format(
        updateTime=update_time, category=category
    )
    columns = pd.read_excel(path, index_col=0)
    for i in range(len(columns)):
        if columnID == columns.iloc[i, 1].split("/")[-1]:
            column_name = columns.iloc[i, 0]
            column_url = columns.iloc[i, 1]
            author_name = columns.iloc[i, 2]
            author_url = columns.iloc[i, 3]
    df = df.to_dict()
    return render_template(
        "beagle/article.html",
        rank=rank,
        columnName=column_name,
        columnUrl=column_url,
        title=column_name,
        category=key_word_dict[category],
        active=category,
        df=df,
        authorName=author_name,
        authorUrl=author_url,
        article_updated_time=article_updated_time,
    )


@zhihu.route("/feedback", methods=["GET", "POST"])
def feedback():
    #descriptions = Feedback
    feedbacks = Feedback.query.order_by(Feedback.id.desc())
    #print(feedbacks)
    if request.method == "POST":
        description = request.form.get("description")
        contact_details = request.form.get("contact_details")
        f = Feedback()
        f.description = description
        f.contact_details = contact_details
        f.save()
        print(description, contact_details)
        flash("反馈提交成功，我们将会尽快处理!")
        return redirect(url_for('zhihu.home'))
    return render_template("beagle/feedback.html", title="反馈", feedbacks=feedbacks, f = "feedback")

@zhihu.route("/documentation")
def documentation():
    return render_template("beagle/documentation.html", docs="docs", title="文档")

app/templates/zhihu/article.html
{% extends "zhihu/base.html" %}
{% block content %}
    <div class="bootstrap_datatables">
        <div class="container py-5">
            <header class="text-center text-black">
                <h1 class=""><a href="{{ columnUrl }}">{{ columnName }}</a></h1>
                         <p class="text-primary m-0 font-weight-bold">创建者：<a href="{{ authorUrl }}">{{ authorName }}</a>
            </p>
            </header>
            <div class="row py-5">
                <div class="col-lg-12 mx-auto">
                    <div class="card rounded shadow border-0">
                        <div class="card-body p-2 bg-white rounded">
                            <div class="table-responsive">
                                <table id="example" style="width:100%" class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>标题</th>
                                        <th>作者</th>
                                        <th>赞同数</th>
                                        <th>评论数</th>
                                        <th>更新时间</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for i in rank %}
                                        <tr>
                                            <td>{{ i+1 }}</td>
                                            <td><a href="{{ articleUrl[i] }}">{{ articleTitle[i] }}</a></td>
                                            <td><a href="{{ articleAuthorUrl[i] }}">{{ articleAuthorName[i] }}</a></td>
                                            <td>{{ articleVoteupCount[i] }}</td>
                                            <td>{{ articleCommentCount[i] }}</td>
                                            <td>{{ articleUpdatedTime[i] }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/zhihu/base.html
<!DOCTYPE html>
<html lang="zh">
<script>
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?7755cea1ce3f2331435d9abccc484b42";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% if title %}
        <title>{{ title }} - Zzmath</title>
    {% else %}
        <title>Zzmath</title>
    {% endif %}
    <link rel="stylesheet" href="../../static/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aleo">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="../../static/assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="../../static/assets/css/Bootstrap-DataTables.css">
    <link rel="stylesheet" href="../../static/assets/css/Footer-Basic.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/assets/css/MUSA_no-more-tables-1.css">
    <link rel="stylesheet" href="../../static/assets/css/MUSA_no-more-tables.css">
    <link rel="icon" href="../../static/favicon.ico" type="image/x-icon">
</head>
<body>
<nav class="navbar navbar-light navbar-expand-md">
    <div class="container-fluid"><a class="navbar-brand" href="{{ url_for("zhihu.home") }}">Zzmath</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse"
             id="navcol-1">
            <ul class="nav navbar-nav">
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "chinese" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="chinese") }}">语文</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "math" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="math") }}">数学</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "english" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="english") }}">英语</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "physics" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="physics") }}">物理</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "chemistry" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="chemistry") }}">化学</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "biology" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="biology") }}">生物</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "political" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="political") }}">政治</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if active == "history" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="history") }}">历史</a>
                </li>
                <li class="nav-item" role="presentation"><a class="nav-link {% if category == "geography" %}active{% endif %}"
                                                            href="{{ url_for("zhihu.index", category="geography") }}">地理</a>
                </li>
                <li class="nav-item" role="presentation"></li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}
<div class="footer-basic">
    <footer class="footer">
        <div class="container">
            <div class="social"><a href="https://www.zhihu.com/people/zerostwo"><i class="fab fa-zhihu"></i></a><a
                    href="https://weibo.com/u/3764641951"><i class="fab fa-weibo"></i></a><a
                    href="https://github.com/zerostwo"><i class="fab fa-github"></i></a><a
                    href="../../static/assets/img/zzmath.png"><i class="fab fa-qq"></i></a></div>
            <p class="copyright">Copyright © <a href="https://zzmath.top" style="color: #aaa">Zzmath</a> 2020
                <img style="width: 16px;vertical-align: sub;" src="../../static/filing.png">
                <a href="http://www.beian.miit.gov.cn" style="color: #aaa">蜀ICP备18027889号</a></p>
        </div>
    </footer>
</div>
<script src="../../static/assets/js/jquery.min.js"></script>
<script src="../../static/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="../../static/assets/js/jquery.dataTables.min.js"></script>
<script src="../../static/assets/js/dataTables.bootstrap4.min.js"></script>
<script src="../../static/assets/js/Bootstrap-DataTables.js"></script>
</body>
</html>

app/templates/zhihu/column.html
{% extends "zhihu/base.html" %}
{% block content %}
    <div class="bootstrap_datatables">
        <div class="container py-5">
            <header class="text-center text-black">
                   <h1 class="">{{ title }}相关专栏排名</h1>
                         <p
                    class="text-primary m-0 font-weight-bold">{{ updateTime[0] }}年{{ updateTime[1] }}月{{ updateTime[2] }}日更新</p>
            </header>
            <div class="row py-5">
                <div class="col-lg-12 mx-auto">
                    <div class="card rounded shadow border-0">
                        <div class="card-bod  p-2 bg-white rounded">
                            <div class="table-responsive">
                                <table id="example" style="width:100%" class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>排名</th>
                                        <th>专栏</th>
                                        <th>创建者</th>
                                        <th>关注数</th>
                                        <th>文章数</th>
                                        <th>得分</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for i in rank %}
                                        <tr>
                                            <td>{{ i }}</td>
                                            <td><a class="card-link" ,
                                                   href="{{ url_for("zhihu.zhuanlan", category=category, columnID=columnIDs[i-1]) }}">{{ columnNames[i-1] }}</a>
                                            </td>
                                            <td><a class="card-link" ,
                                                   href="{{ authorUrls[i-1] }}">{{ authorNames[i-1] }}</a>
                                            </td>
                                            <td>{{ followers[i-1] }}</td>
                                            <td>{{ articlesCounts[i-1] }}</td>
                                            <td>{{ columnScores[i-1] }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/zhihu/home.html
{% extends "zhihu/base.html" %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center" id="main">
        <h1 class="mr-3 pr-3 align-top border-right inline-block align-content-center">404</h1>
        <div class="inline-block align-middle">
            <h2 class="font-weight-normal lead" id="desc">The page you requested was not found.</h2>
        </div>
    </div>
{% endblock %}